[package]
name = "perceptron_cli"
version = "1.0.0"
authors = ["dakatk <dakatk97@gmail.com>"]
edition = "2018"

[dependencies]
rand = "^0.7.3"
approx = "^0.3.2"
ndarray = { version = "^0.13.1", default-features = false, features = ["blas", "approx"] }
blas-src = { version = "^0.2.0", default-features = false, features = ["accelerate"] }
openblas-src = { version = "^0.6.0", default-features = false, features = ["cblas", "system"] }
ndarray-rand = "^0.11.0"

[profile.dev]
debug = true
opt-level = 1

[profile.release]
debug = false
opt-level = 3