[package]
name = "perceptron_cli"
version = "1.0.0"
authors = ["dakatk <dakatk97@gmail.com>"]
edition = "2018"

#[target.'cfg(target_os = "macos")'.dependencies]
#blas-src = { version = "^0.2.0", default-features = false, features = ["accelerate"] }

[dependencies]
rand = "^0.7.3"
approx = "^0.3.2"
serde_json = "^1.0.57"
ndarray = { version = "^0.13.1", features = ["approx", "serde"] }
ndarray-rand = "^0.11.0"
clap = "^2.33.3"

[profile.dev]
debug = true
opt-level = 1

[profile.release]
debug = false
opt-level = 3