[package]
name = "nn_cli"
version = "0.1.0"
authors = ["dakatk <dakatk97@gmail.com>"]
edition = "2018"

[dependencies]
rand = "^0.7.3"
ndarray = { version = "^0.13.1", default-features = false, features = ["blas", "approx"] }
approx = { version = "^0.3.2", optional = false }
blas-src = { version = "^0.2.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "^0.6.0", default-features = false, features = ["cblas", "system"] }
ndarray-rand = "^0.11.0"